musicstore3/Controllers/ShoppingCartController.cs
using musicstore3.Models;
using musicstore3.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace musicstore3.Controllers
{
    public class ShoppingCartController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }

        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
	}
}

musicstore3/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using musicstore3.Models;

namespace musicstore3.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        
        //
        // GET: /Store/

        public ActionResult Index()
        {

            var genres = storeDB.Genres.ToList();

         /*   var genres = new List<Genre>{

                new Genre {Name="Disco"},
                new Genre {Name="Jazz"},
                new Genre {Name="Rock"}

            };*/

            return View(genres);
        }

        public ActionResult Browse(string genre)
        {
          //  var genreModel = new Genre { Name = genre };
            var genreModel = storeDB.Genres.Include("Albums").Single(g => g.Name == genre);
            return View(genreModel);

        }

        public ActionResult Details(int id)
        {
        //    var album = new Album { Title = "Album " + id };

            var album = storeDB.Albums.Find(id);
            return View(album);
        }

       
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();
            return PartialView(genres);
        }

    }
}

musicstore3/Views/Store/Browse.cshtml
@model musicstore3.Models.Genre

@{
    ViewBag.Title = "Browse Albums";
}

<div class="genre">
    <h3><em>@Model.Name</em> Albums</h3>
    <ul id="album-list">
        @foreach (var album in Model.Albums)
        {
            <li>
                <a href="@Url.Action("Details",
                    new { id = album.AlbumId })">
                    <img alt="@album.Title"
                         src="@album.AlbumArtUrl" />
                    <span>@album.Title</span>
                </a>
            </li>
        }

        </ul>

</div>

musicstore3/Views/Store/Details.cshtml
@model musicstore3.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Album: @Model.Title</h2>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Artist:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}",
Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add tocart", "AddToCart", "ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
</div>

musicstore3/Views/Store/GenreMenu.cshtml
@model IEnumerable<musicstore3.Models.Genre>

    <ul id="categories">
        @foreach (var genre in Model)
        {
            <li>
                @Html.ActionLink(genre.Name,    "Browse", "Store", new { Genre = genre.Name }, null)
        </li>
        }
    </ul>

musicstore3/Views/Store/Index.cshtml
@model IEnumerable<musicstore3.Models.Genre>

@{
    ViewBag.Title = "Index";
}

<h3>Browse Genres</h3>

<p>Select form @Model.Count()</p>

@foreach(var genre in Model){
    
    
    <li>@Html.ActionLink(genre.Name,"Browse", new { genre = genre.Name })</li>

}